####################################################
#                                                  #
#              Living Room (Room 11)               #
#                                                  #
####################################################  


    
automation:
    

  - id: 'announcement_10'
    alias: "announcement_10"
    trigger:
      at: '7:00:00'
      platform: time
    action:
    - service: script.speak_time_daily

  - id: 'announcement_12'
    alias: "announcement_12"
    trigger:
      platform: event
      event_type: feedreader
    condition:
      condition: or
      conditions:
        - condition: time
          after: '8:00'
          before: '12:00'
        - condition: time
          after: '13:30'
          before: '19:00'  
    action:
    # - service: script.news_update
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.6'
    - service: tts_viettel.say
      data_template:
        message: "Có tin mới buổi {{ states('sensor.sys_buoi') }} lúc {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p, %d/%m/%Y', true) }} với tựa đề {{ trigger.event.data.title }} 
        và nội dung {{ trigger.event.data.description }}"                
        entity_id: media_player.van_phong        
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  


  - id: single_button_press
    alias: 'single_button_press'    
    trigger:
      platform: state 
      entity_id: sensor.zb_bt_01_click
      to: 'single'  
    condition:
      condition: time
      after: '5:30'
      before: '22:30'  
    action:
     service: script.lucky_number

  - id: double_button_press
    alias: 'double_button_press'    
    trigger:
      platform: state 
      entity_id: sensor.zb_bt_01_click
      to: 'double'  
    condition:
      condition: time
      after: '5:30'
      before: '22:30'  
    action:
     service: script.check_outdoor       

  - id: triple_button_press
    alias: 'triple_button_press'    
    trigger:
      platform: state 
      entity_id: sensor.zb_bt_01_click
      to: 'triple'  
    condition:
      condition: time
      after: '5:30'
      before: '22:30'  
    action:
     service: script.corona_speak      

  - id: 'speak_corona_update_1'
    alias: "speak_corona_update_1"
    trigger:
      platform: state
      entity_id: sensor.worldwide_coronavirus_confirmed      
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"      
    action:
      service: script.corona_speak

  - id: 'speak_corona_update_2'
    alias: "speak_corona_update_1"
    trigger:
      platform: state
      entity_id: sensor.us_coronavirus_confirmed      
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"      
    action:
      service: script.corona_speak

  - id: 'Call Script'
    alias: Call Script
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
      service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'
        
script:

  speak_time_daily:
    sequence:  
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.6'        
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là bảy giờ sáng, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong        
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là tám giờ sáng, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là chín giờ sáng, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là mười giờ sáng, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là mười một giờ sáng, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là mười hai giờ trưa, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 02:00:00
    - service: tts_viettel.say      
      data_template:
        message: "Bây giờ là hai giờ chiều, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 01:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là ba giờ chiều, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 01:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là bốn giờ chiều, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00    
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là năm giờ chiều, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là sáu giờ chiều, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 1:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là bẩy giờ tối, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 01:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là tám giờ tối, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 01:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là chín giờ tối, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 01:00:00
    - service: tts_viettel.say
      data_template:
        message: "Bây giờ là mười giờ tối, nhiệt độ phòng là {{states('sensor.zb_tem_hum_01_temperature')}} độ xê, độ ẩm phòng là {{states('sensor.zb_tem_hum_01_humidity')}} phần trăm"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'  
    - delay: 00:05:00
    - service: tts_viettel.say
      data_template:
        message: "Chúc ngủ ngon "          
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'    

  lucky_number:
    sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.6'
    - service_template: tts_viettel.say
      data_template:
        message: '{{["Em gửi các anh các chị con số ngẫu nhiên này" , "Con số ngẫu nhiên em gửi cho là" , "Ngẫu nhiên lúc này em cho số là" , "Em cho số ngẫu nhiên này" , "Em  gửiđây là 1 con số ngẫu nhiên" , "Số ngẫu nhiên là em cho" ] |random + ["01" , "02" , "03" , "04" , "05", "06", "07", "08", "09", "10" , "11" , "12" , "13" , "14" , "15", "16", "17", "18", "19", "20" , "21" , "22" , "23" , "24" , "25", "26", "27", "28", "29", "30" , "31" , "32" , "33" , "34" , "35", "36", "37", "38", "39", "40" , "41" , "42" , "43" , "44" , "45", "46", "47", "48", "49", "50" , "51" , "52" , "53" , "54" , "55", "56", "57", "58", "59", "60" , "61" , "62" , "63" , "64" , "65", "66", "67", "68", "69", "70" , "71" , "72" , "73" , "74" , "75", "76", "77", "78", "79", "80", "81" , "82" , "83" , "84" , "85", "86", "87", "88", "89", "90" , "91" , "92" , "93" , "94" , "95", "96", "97", "98", "99"] |random }} '
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1' 
  corona_speak:
    sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.6'
    - service: tts_viettel.say    
      data_template:        
        message: "Cập nhật thông tin về dịch Cô vít 19, số ca nhiễm thế giới là {{states('sensor.worldwide_coronavirus_confirmed')}} ca, Mỹ là {{states('sensor.us_coronavirus_confirmed')}} ca, Việt Nam là {{states('sensor.vietnam_coronavirus_confirmed')}} ca, số ca nhiễm hôm nay là {{states.sensor.worldwide_coronavirus_current.state}} ca, Mỹ là {{states('sensor.us_coronavirus_current')}} ca, Việt Nam là {{states('sensor.vietnam_coronavirus_current')}} ca, số ca tử vong là {{states.sensor.worldwide_coronavirus_deaths.state}} ca, Mỹ là {{states('sensor.us_coronavirus_deaths')}} ca, Việt Nam là {{states('sensor.vietnam_coronavirus_deaths')}} ca, số ca chữa khỏi là {{states.sensor.worldwide_coronavirus_recovered.state}} ca, Mỹ là {{states('sensor.us_coronavirus_recovered')}} ca, Việt Nam là {{states('sensor.vietnam_coronavirus_recovered')}} ca"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'          
        
  check_indoor:
    sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.8'
    - service: tts_viettel.say    
      data_template:
        message: "Hiện tại là {{ states('sensor.sys_thu_ngay_thang') }} buổi {{ states('sensor.sys_buoi') }} thời gian là {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p', true) }}"
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'          

  check_outdoor:
    sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.van_phong
        volume_level: '0.8'
    - service: tts_viettel.say    
      data_template:    
        message: "Hiện tại là {{ states('sensor.sys_thu_ngay_thang') }} buổi {{ states('sensor.sys_buoi') }} thời gian là {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p', true) }}, thông tin thời tiết chung tại khu vực là {{states('sensor.out_weather_forecast')}}, nhiệt độ là {{states('sensor.out_weather_temperature')}} độ xê, tốc độ gió là {{states('sensor.out_weather_wind_speed')}} mét trên giây, áp suất không khí là {{states('sensor.out_weather_pressure')}} mbar"   
        entity_id: media_player.van_phong
        voice_type: '{{["nu_mien_bac_1" , "nu_mien_bac_2" , "nu_mien_trung_1" , "nu_mien_nam_1" , "nu_mien_nam_2" , "nu_mien_nam_3", "nam_mien_bac_1", "nam_mien_bac_2", "nam_mien_trung_1", "nam_mien_nam_1" ] |random }} '
        speed: '1'           
 
